_wandb:
    value:
        cli_version: 0.24.2
        e:
            8hs7n1495bb8ijsx7ery3tqzhc43jzh8:
                codePath: word2vec/train.py
                codePathLocal: train.py
                email: sh4421@columbia.edu
                executable: /Users/apple/Desktop/Classes/2026 Spring/NLP/Homeworks/HW1/hw1/.venv/bin/python3
                git:
                    remote: https://github.com/HenryWashuHe/COMS-4705-NLP-HW1.git
                host: Henrys-MacBook-Pro.local
                os: macOS-26.2-arm64-arm-64bit-Mach-O
                program: /Users/apple/Desktop/Classes/2026 Spring/NLP/Homeworks/HW1/hw1/word2vec/train.py
                python: CPython 3.14.0
                root: /Users/apple/Desktop/Classes/2026 Spring/NLP/Homeworks/HW1/hw1/word2vec
                startedAt: "2026-02-11T02:33:39.042924Z"
                writerId: 8hs7n1495bb8ijsx7ery3tqzhc43jzh8
        m: []
        python_version: 3.14.0
        t:
            "1":
                - 1
                - 5
                - 49
                - 51
                - 53
            "2":
                - 1
                - 5
                - 49
                - 51
                - 53
            "3":
                - 16
            "4": 3.14.0
            "5": 0.24.2
            "8":
                - 2
            "12": 0.24.2
            "13": darwin-arm64
batch_size:
    value: 128
embedding_dim:
    value: 64
learning_rate:
    value: 0.1
num_epochs:
    value: 15
vocab_size:
    value: 5001
